AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: SAM Fotos eCommerce

Parameters:
  PhotosBucketName:
    Type: String
    Description: "Nombre del Bucket S3"

Resources:
  PhotosTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: key
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: key
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      TableName: !Sub ${AWS::StackName}-Photos

  Put:
    Type: AWS::Serverless::Function
    Properties:
      Handler: put.handler
      Runtime: python3.7
      CodeUri: src/
      FunctionName: !Sub ${AWS::StackName}-put_photo
      Description: "Crea un elemento en DynamoDB a partir de eventos S3 ObjectCreated:*."
      Tracing: Active
      MemorySize: 1024
      Policies:
        - AWSXrayWriteOnlyAccess
        - AWSLambdaExecute
        - DynamoDBCrudPolicy:
            TableName: !Ref PhotosTable
      Environment:
        Variables:
          TABLE_NAME: !Ref PhotosTable
          TABLE_ARN: !GetAtt PhotosTable.Arn

  Delete:
    Type: AWS::Serverless::Function
    Properties:
      Handler: delete.handler
      Runtime: python3.7
      CodeUri: src/
      FunctionName: !Sub ${AWS::StackName}-delete_photo
      Description: "Elimina un elemento en DynamoDB a partir de eventos S3 ObjectRemoved:*."
      Tracing: Active
      MemorySize: 1024
      Policies:
        - AWSXrayWriteOnlyAccess
        - AWSLambdaExecute
        - DynamoDBCrudPolicy:
            TableName: !Ref PhotosTable
      Environment:
        Variables:
          TABLE_NAME: !Ref PhotosTable
          TABLE_ARN: !GetAtt PhotosTable.Arn

  ExportCSV:
    Type: AWS::Serverless::Function
    Properties:
      Handler: export.handler
      Runtime: python3.7
      CodeUri: src/
      FunctionName: !Sub ${AWS::StackName}-export_csv
      Description: "Genera volcado de contenido a un archivo CSV."
      Tracing: Active
      MemorySize: 1024
      Timeout: 60
      Policies:
        - AWSXrayWriteOnlyAccess
        - AWSLambdaExecute
        - S3CrudPolicy:
            BucketName: !Sub ${PhotosBucketName}
        - DynamoDBCrudPolicy:
            TableName: !Ref PhotosTable
      Environment:
        Variables:
          TABLE_NAME: !Ref PhotosTable
          TABLE_ARN: !GetAtt PhotosTable.Arn
          BUCKET_NAME: !Sub ${PhotosBucketName}
